data_path: data/raw/melbourne_housing.csv
target: Price
focus_suburbs:
- Malvern East
- Malvern
- Glen Iris
- Ashburton
- Carnegie
- Murrumbeena
- Chadstone
- Hughesdale
- Caulfield North
- Caulfield South
- Caulfield East
- Armadale
test_size: 0.2
random_state: 42
model:
  type: RandomForestRegressor
  params:
    n_estimators: 400
    max_depth: null
    n_jobs: -1
    random_state: 42
numeric_features:
- Rooms
- Distance
- Propertycount
- Landsize
- BuildingArea
- YearBuilt
- Bathroom
- Car
- Postcode
categorical_features:
- Suburb
- Type
- Method
- CouncilArea
- Regionname
date_feature: Date
